spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.125.14:33099/sky_take_out?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 147258369
  data:
    redis:
      host: 47.99.125.14
      port: 4406
      password: 123456
      database: 1

sky:
  jwt:
    admin-secret-key: itcast
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: itheima
    user-token-name: authentication
    user-ttl:  7200000
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tBA3YQpo4XPfsiEkPes
    access-key-secret: WwBm59P8BJjhDmS9bUivaQxN4rOYqC
    bucket-name: databyjavaweb
  wechat:
    appid: wxd1e69dc33761c823
    secret: 638df9e297c0aa219b90f35cf0b5313f
    mchid: 1561414331
    mch-serial-no: 4B3B3DC35414AD50B18755BAF8DE9CC7CF407606
    private-key-file-path: D:/pay/apiclient_key.pem
    api-v3-key: CZBK51236435wxpay435434323FFDuv3
    we-chat-pay-cert-file-path: D:/pay/wechatpay_166096F876F45C7D07CE98952A96EC980368ACFC.pem
    notify-url: https://6619cf50.r6.cpolar.top/notify/paySuccess
    refund-notify-url: https://6619cf50.r6.cpolar.top/notify/refundSuccess
