spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:// xxxxxx/aipel-hub?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
#    url: jdbc:mysql://xxxxxx/sky_take_out?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: xxxxxx
  data:
    redis:
#      host: redis
      host: xxxxxx
#      port: 6379
      port:xxxxx
      password: 123456
      database: 1

sky:
  jwt:
    admin-secret-key: itcast
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: itheima
    user-token-name: authentication
    user-ttl:  7200000
  alioss:
    endpoint: xxxx
    access-key-id: xxxxx
    access-key-secret: xxxxx
    bucket-name: xxxxxx
  wechat:
    appid: xxxxxx
    secret: xxxxxx
    mchid: xxxx
    mch-serial-no: 4B3B3DC35414AD50B18755BAF8DE9CC7CF407606
    private-key-file-path: D:/pay/apiclient_key.pem
    api-v3-key: CZBK51236435wxpay435434323FFDuv3
    we-chat-pay-cert-file-path: D:/pay/wechatpay_166096F876F45C7D07CE98952A96EC980368ACFC.pem
    notify-url: https://6619cf50.r6.cpolar.top/notify/paySuccess
    refund-notify-url: https://6619cf50.r6.cpolar.top/notify/refundSuccess
